### ISSUE TITLE
DeprecationWarning when creating a new Configuration object

### ISSUE THREAD

**Issue by mostafa-helmy-sp** [sailpoint-oss/typescript-sdk#37]
This is the line of code generating the warning:
`const apiConfig = new Configuration()`

The warning received:
`(node:22088) [DEP0044] DeprecationWarning: The 'util.isArray' API is deprecated. Please use 'Array.isArray()' instead.
(Use 'node --trace-deprecation ...' to show where the warning was created)
DeprecationWarning: The 'util.isArray' API is deprecated. Please use 'Array.isArray()' instead.
    at FormData.append (.\node_modules\form-data\lib\form_data.js:64:12)
    at new Configuration (.\node_modules\sailpoint-api-client\configuration.ts:140:22)`

**Comment by tyler-mairose-sp** [comment]
Hey @mostafa-helmy-sp, I dug into this and we rely on a form-data package where this deprecation is thrown. They have a PR out for fixing this, once it is merged in we can update to the latest version. I will keep an eye out on it. https://github.com/form-data/form-data/issues/563

Thank you for bringing it to our attention!
